apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-addon
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: {{ .Values.cluster }}
  project: {{ .Values.project }}
  source:
    path: cluster-addons-chart
    repoURL: https://github.com/CourageOI/example.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - CreateNamespace=true