apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-addons
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: {{ .Values.cluster }}
  project: {{ .Values.project }}
  source:
    path: eks-cluster-addons-chart
    repoURL: https://github.com/hivenetes/k8s-bootstrapper
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - CreateNamespace=true